spring:
      jpa:
      show-sql: true
      hibernate:
        ddl-auto: validate
      profiles:
        active: dev
      initialization-mode: always

      thymeleaf:
          mode: HTML
      devtools:
        restart:
          exclude: templates/**,static/**
# kafka
      kafka:
        bootstrap-servers: 192.168.0.115:9092
        consumer:
          group-id: xunwu
server:
  error:
    whitelabel:
      enabled: false
