spring:
      jpa:
      show-sql: true
      hibernate:
        ddl-auto: validate
      profiles:
        active: dev
      initialization-mode: always

      thymeleaf:
          mode: HTML
      devtools:
        restart:
          exclude: templates/**,static/**

      redis:
        database: 0
        host: 192.168.0.113
        port: 6379
        jedis:
          pool:
            min-idle: 1
            max-active: 10000
        timeout: 3000
      session:
        store-type: redis
server:
  error:
    whitelabel:
      enabled: false
