
spring:
  datasource:
        hikari:
          jdbc-url:  jdbc:mysql://localhost:3306/xunwu?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: 123456
          initialSize : 20
          maxActive : 50
          maxIdle : 20
          minIdle : 10
          maxWait : 10
          defaultAutoCommit : true
          minEvictableIdleTimeMillis : 3600000

  servlet:
    multipart:
      enabled: true
      location: D:\DataSpace\xunwu-project\tmp\
      file-size-threshold: 5MB
      max-request-size: 20MB
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/

logging:
  level:
    org:
      hibernate:
        SQL: debug
