spring:
  datasource:
          hikari:
                driver-class-name: org.h2.Driver
                jdbc-url: jdbc:h2:mem:test
          schema: classpath:db/schema.sql
          data: classpath:db/data.sql